name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-production:
    name: Deploy production
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & tag docker image
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/docker-build-tag-push@main
        with:
          environment: production
          push: true

      - name: Trigger deploy
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/trigger-workflow-and-wait@main
        with:
          application-id: ${{ secrets.TVARKAU_LIETUVA_TRIGGER_DEPLOY_APPLICATION_ID }}
          application-private-key: ${{ secrets.TVARKAU_LIETUVA_TRIGGER_DEPLOY_APPLICATION_PRIVATE_KEY }}
          repository: ${{ secrets.TVARKAU_LIETUVA_TRIGGER_DEPLOY_REPOSITORY }}
          workflow-file-name: ${{ secrets.TVARKAU_LIETUVA_TRIGGER_DEPLOY_WORKFLOW_FILE_NAME }}
          workflow-payload: '{"environment": "production"}'
